theme: jekyll-theme-minimal
title: Club de Ajedrez
logo: https://scontent.fgua5-1.fna.fbcdn.net/v/t1.6435-9/92496568_1492664217569907_298664874643292160_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=tImFVPW5jYoAX8pidg0&_nc_ht=scontent.fgua5-1.fna&oh=01cac9dd965b66898582686217047106&oe=60AA66EB
description: “Chess, like love, like music, has the power to make men happy.” – Siegbert Tarrasch
